// Generated by CoffeeScript 1.6.3
(function() {
  var _defaults, _for_now_updater;

  _defaults = {
    interval: 60,
    selector: '[role="time"]'
  };

  _for_now_updater = function($el, selector) {
    return function() {
      return $el.find(selector).each(function(i, obj) {
        var time;
        if (time = $el.find(obj).data('time')) {
          return $el.find(obj).html(moment(time).fromNow());
        }
      });
    };
  };

  this.actual_time = function(options) {
    var $;
    if ((options != null) && (options.$el != null)) {
      $ = options.$el;
    } else if (typeof jQuery !== "undefined" && jQuery !== null) {
      $ = jQuery;
    } else {
      return console.log('actual_time unable to bind jQuery function. exiting...');
    }
    if (typeof $ === "function") {
      $ = $('body');
    }
    options = $.extend({}, _defaults, options);
    _for_now_updater($, options.selector).call();
    return setInterval(_for_now_updater($, options.selector), options.interval * 1000);
  };

  this.set_actual_time = function(options) {
    var $, time;
    time = moment().format();
    $ = options.$el;
    options = $.extend({}, _defaults, options);
    $.find(options.selector).each(function(i, obj) {
      $.find(obj).data('time', time);
      return $.find(obj).attr('data-time', time);
    });
    return _for_now_updater($, options.selector).call();
  };

}).call(this);
